version: '3'

services:
  go:
    container_name: go
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - gohome:/home/devcontainer/go:cached
    environment:
      - TZ=Asia/Tokyo
    env_file:
      - ./go-workplace-3/.env
    tty: true
    user: devcontainer
    depends_on:
      - db

  db:
    container_name: db
    
    build: 
      context: .
      dockerfile: ./docker/db/Dockerfile
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

    env_file:
      - ./go-workplace-3/.env
    volumes:
      - mysql_data:/var/lib/mysql
      - ./go-workplace-3/conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./go-workplace-3/sql:/sql
    ports:
      - 13306:3306
    networks:
      - default

volumes:
  gohome:
  mysql_data:
    driver: local

networks:
  default:
