version: '3'

services:
  go:
    container_name: go
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - gohome:/home/devcontainer/go:cached
    environment:
      - TZ=Asia/Tokyo
    tty: true
    user: devcontainer

volumes:
  gohome:
