version: '3'

services:
  go:
    container_name: go
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    env_file:
      - ./goapp/.go_env
    environment:
      - TZ=Asia/Tokyo
    tty: true
